### ISSUE TITLE
Useful methods on Plotter

### ISSUE THREAD

**Issue by AldaronLau** [DougLau/footile#27]
For reusing a `Plotter` to reduce number of allocations, it's necessary to clear the contained `Raster` before each composite.  The way this must be done currently is:

```rust
let mut pr = p.raster();
pr.clear();
p = Plotter::new(pr);
p.set_transform(Transform::{...}); // Reset the transform
```

It would be more elegant to have an API to do either:

```rust
p.raster_mut().clear();
```

or

```rust
p.clear();
```

**Comment by DougLau** [comment]
Added in https://github.com/DougLau/footile/commit/4600d98448ea8d2b0a30f24f795b5ab1295b57d1
