### ISSUE TITLE
Add support for filling with image or gradient sources

### ISSUE THREAD

**Issue by jrmuizel** [DougLau/footile#6]
This is an important piece of functionality for a 2d library. I have been playing around with the code needed to support this kind of thing here: https://github.com/jrmuizel/sw-composite/blob/master/src/lib.rs

Feel free to crib anything from it that you'd like.

**Comment by DougLau** [comment]
I agree this would be a good thing to have.  I'm looking into color space support, which would be good to figure out before adding gradients.

**Comment by jrmuizel** [comment]
What do you have in mind for color space support?

**Comment by DougLau** [comment]
Color blending in RGB is not very satisfying.  See the palette crate for some examples.  I would like to use that, but I don't know if it can be made performant.  For now, I want to make a ColorSpace trait, with one Rgba32 type.  Other spaces can be added as needed.

**Comment by jrmuizel** [comment]
I think it will be hard to be performant. I believe Skia has looked at the approximation of sRGB that's just x^2/sqrt(x) and even that isn't on by default.

**Comment by DougLau** [comment]
This feature should be in the pix crate.
