### ISSUE TITLE
Allow widths not divisible by 4

### ISSUE THREAD

**Issue by DougLau** [DougLau/footile#9]
Currently, Raster and Mask widths are assumed to be divisible by 4.

**Comment by jrmuizel** [comment]
FWIW, cairo/pixman forces the stride of images to be divisble by 4 bytes. i.e. a 3x3 A8 bitmap will be stored in memory as 4x3 bytes. Not having to worry about smaller alignments can be useful for performance because you can always treat everything as some number of u32s

**Comment by DougLau** [comment]
Interesting.  For this issue, I just want to add some tests to make sure all widths are supported.

**Comment by DougLau** [comment]
This is handled by pix crate now.
